// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData, PositionTableId } from "./tables/Position.sol";
import { Health, HealthData, HealthTableId } from "./tables/Health.sol";
import { Strength, StrengthTableId } from "./tables/Strength.sol";
import { EntityInfo, EntityInfoData, EntityInfoTableId } from "./tables/EntityInfo.sol";
import { EntityOwnership, EntityOwnershipTableId } from "./tables/EntityOwnership.sol";
import { EntityMarketplaceSell, EntityMarketplaceSellData, EntityMarketplaceSellTableId } from "./tables/EntityMarketplaceSell.sol";
import { StakingRecord, StakingRecordData, StakingRecordTableId } from "./tables/StakingRecord.sol";
